BloggerBlogBundle_homepage:
    pattern:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        _method:  GET
                
BloggerBlogBundle_about:
    pattern:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method:  GET
        
BloggerBlogBundle_contact:


    pattern:  /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
        _method:  GET

BloggerBlogBundle_create:
    pattern:  /create
    defaults: { _controller: BloggerBlogBundle:Restaurant:createRestaurant }
    requirements:
        _method:   GET|POST

search:
    pattern:  /search
    defaults: { _controller: BloggerBlogBundle:Search:executeSearch }
    requirements:
        _method:  GET|POST


